# Auto-generated by run_sim.ps1 on 2025-11-13T11:24:56
# UI가 이 시뮬( 127.0.0.1:5020 / Unit=1 )에 붙도록 환경 주입
$env:ESA_BACKEND      = "MODBUS"
$env:MODBUS_PROTOCOL  = "tcp"
$env:MODBUS_TCP_HOST  = "127.0.0.1"
$env:MODBUS_TCP_PORT  = "5020"
$env:MODBUS_UNIT_ID   = "1"
$env:MODBUS_POLL_MS   = "500"
$env:MODBUS_START_SIM = "0"   # UI 내부 시뮬 OFF (외부 시뮬로만)
