"""add_rtu_models

Revision ID: eb44086cf9ba
Revises: 
Create Date: 2026-01-19 11:55:48.449548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb44086cf9ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rtu_ack_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('alarms_acked', sa.Integer(), nullable=True),
    sa.Column('sessions_acked', sa.Integer(), nullable=True),
    sa.Column('client_host', sa.String(), nullable=True),
    sa.Column('snapshot_before', sa.Text(), nullable=True),
    sa.Column('snapshot_after', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rtu_alarm_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('baudrate', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('age_sec', sa.Float(), nullable=True),
    sa.Column('stale_threshold_sec', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('acked', sa.Integer(), nullable=True),
    sa.Column('acked_at', sa.Float(), nullable=True),
    sa.Column('acked_by', sa.String(), nullable=True),
    sa.Column('ack_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rtu_alarm_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('start_ts', sa.Float(), nullable=False),
    sa.Column('end_ts', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('enter_alarm_id', sa.Integer(), nullable=True),
    sa.Column('exit_alarm_id', sa.Integer(), nullable=True),
    sa.Column('acked', sa.Integer(), nullable=True),
    sa.Column('acked_at', sa.Float(), nullable=True),
    sa.Column('acked_by', sa.String(), nullable=True),
    sa.Column('ack_note', sa.Text(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('baudrate', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rtu_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('last_success_at', sa.Float(), nullable=True),
    sa.Column('connected', sa.Integer(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('baudrate', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_read_ms', sa.Float(), nullable=True),
    sa.Column('last_write_ms', sa.Float(), nullable=True),
    sa.Column('write_q_size', sa.Integer(), nullable=True),
    sa.Column('ingest_q_size', sa.Integer(), nullable=True),
    sa.Column('db_q_size', sa.Integer(), nullable=True),
    sa.Column('read_ok_rate_60s', sa.Float(), nullable=True),
    sa.Column('write_ok_rate_60s', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rtu_write_cmd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('addr', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hud_accent_rgb', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_theme')
    op.drop_table('rtu_write_cmd')
    op.drop_table('rtu_health')
    op.drop_table('rtu_alarm_session')
    op.drop_table('rtu_alarm_log')
    op.drop_table('rtu_ack_audit')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
